export interface Bookmark {
  id: string;
  title: string;
  description: string;
  image: string | null;
  /* author: string; */
  type: string | null;
  url: string;
  domain: string;
  canonicalUrl: string;
  followsRedirect: boolean;
  user_id: string;
  contentInMarkdown: string;
  // TODO: we don't need to populate() in this case
  tags: string[];
  // auto-generated by mongoose timestamp option
  createdAt: string;
  updatedAt: string;
  // fields added by mongoose_delete plugin
  deleted?: boolean;
  deletedAt: string;
}
